import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation/header";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import LeftText from "@/components/left-text";
import RightText from "@/components/right-text";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LeftText />
          <RightText />
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
